#!/bin/bash

#cal | grep --before-context 6 --after-context 6 --color -e " $(date +%e)" -e "^$(date +%e)"

day=$(date +%e)

disp=`cal | \
# delete blank line -> remove block on current day -> color current day -> padding space at line beginning
sed -e '/^$/d' \
-e "s/_//g" \
-e "s/\(^$day\)/"$'\e[33;40m'"\1"$'\e[;40m'"/g" \
-e "2,8s/\( $day\)/"$'\e[33;40m'"\1"$'\e[;40m'"/g" \
-e "s/^/"$'\e[;40m'"          /g"`

echo $'\e[;40m'"$disp                                 "$'\e[0m'
