#!/bin/bash

#cal | grep --before-context 6 --after-context 6 --color -e " $(date +%e)" -e "^$(date +%e)"

day=$(date +%e)

disp=`cal | \
# delete blank line
sed -e '/^$/d' | \
# highlight current day
sed "2,8s/\([ ^]$day\)/"$'\e[33;40m'"\1"$'\e[;40m'"/g" | \
# padding space at line beginning
sed "s/^/"$'\e[;40m'"          /g"`

echo $'\e[;40m'"$disp                                 "$'\e[0m'
